[package]
name = "multi_owner"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dag_mut"
path = "src/dag_mut.rs"

[[bin]]
name = "spawn"
path = "src/spawn.rs"

[[bin]]
name = "weak_reference"
path = "src/weak_reference.rs"

[dependencies]
