[package]
name = "scrape_url"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "scrape_url"
path = "src/scrape_url.rs"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
html2md = "0.2"
